name: Adruva Resto CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        working-directory: ./api
        run: npm install
      - name: Build
        working-directory: ./api
        run: npm run build

  test-superadmin-app:
    name: Build SuperAdmin App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        working-directory: ./superadmin-app
        run: npm install
      - name: Build
        working-directory: ./superadmin-app
        run: npm run build

  test-chain-app:
    name: Build Chain App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        working-directory: ./chain-app
        run: npm install
      - name: Build
        working-directory: ./chain-app
        run: npm run build

  test-outlet-app:
    name: Build Outlet App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        working-directory: ./outlet-app
        run: npm install
      - name: Build
        working-directory: ./outlet-app
        run: npm run build

  test-customer-app:
    name: Build Customer App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Dependencies
        working-directory: ./customer-app
        run: npm install
      - name: Build
        working-directory: ./customer-app
        run: npm run build
